# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7b071bf3c930a7d04299ea5268e2d8789631d72b787d1fee0c23c14f885afde12f44908d045134e10b196941b1fd466b0c17310ec5780155c3c586754bf518b

test:
  secret_key_base: 3cc3fa1f36d08a480779f45ae41bee7462d56687b31ee8dac2041036595b70d965c461167c36ad6bf4c0fe457c88715008ed29c9a3f482564c42c3be1165305e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
